#ifndef     VL60_CONTROLS_H
#define     VL60_CONTROLS_H

//------------------------------------------------------------------------------
//
//------------------------------------------------------------------------------
enum
{
    CTRL_TUMBLER_PNT = 100,
    CTRL_TUMBLER_PNT1 = 101,
    CTRL_TUMBLER_PNT2 = 102,
    CTRL_MAIN_SWITCH_ON = 103,
    CTRL_RETURN_PROTECTION = 104,
    CTRL_TUMBLER_FR = 105,
    CTRL_TUMBLER_MK = 106,
    CTRL_TUMBLER_MV1 = 107,
    CTRL_TUMBLER_MV2 = 108,
    CTRL_TUMBLER_MV3 = 109,
    CTRL_TUMBLER_MV4 = 110,
    CTRL_TUMBLER_MV5 = 111,
    CTRL_TUMBLER_MV6 = 112,
    CTRL_TUMBLER_CU = 113,
    CTRL_TUMBLER_SPOT_HIGH = 114,
    CTRL_TUMBLER_SPOT_LOW = 115,
    CTRL_TUMBLER_CAB_LIGHT_LOW = 116,
    CTRL_TUMBLER_CAB_LIGHT_HIGH = 117,
    CTRL_TUMBLER_LIGHT_DEVICES = 118,
    CTRL_TUMBLER_BUF_LIGHT_L = 119,
    CTRL_TUMBLER_BUF_LIGHT_R = 120,
    CTRL_TUMBLER_BUF_COLOR_L = 121,
    CTRL_TUMBLER_BUF_COLOR_R = 122,
    CTRL_TUMBLER_EPB = 123,
    CTRL_REVERS_INSERTION = 124,
    CTRL_EPK_INSERTION = 125,
    CTRL_LOCK_367_INSERTION = 126,
    CTRL_KEY_EPK = 127,
    CTRL_REVERS_POSITION = 128,
    CTRL_KM_MAIN_POSITION = 129,
    CTRL_KRM_395 = 130,
    CTRL_KVT_254 = 131,
    CTRL_COMBINE_KRAN = 132,
    CTRL_SAND_BUTTON = 133,
    CTRL_WHISTLE_BUTTON = 134,
    CTRL_TIFON_BUTTON = 135,
    CTRL_RBS_BUTTON = 136,
    CTRL_RB_BUTTON = 137,
    CTRL_RBP_BUTTON = 138,
    CTRL_AUTOPILOT = 139,
    CTRL_SHUNTING_MODE = 140,

    // Концевые краны тормозной магистрали
    CTRL_ANGLECOCK_BP_FWD = 141,
    CTRL_ANGLECOCK_BP_BWD = 142,

    // Концевые краны питательной магистрали
    CTRL_ANGLECOCK_FL_FWD = 143,
    CTRL_ANGLECOCK_FL_BWD = 144,

    // Концевые краны тормозных цилиндров
    CTRL_ANGLECOCK_BC_FWD = 145,
    CTRL_ANGLECOCK_BC_BWD = 146,
};

#endif
