#ifndef ACTION_H
#define ACTION_H

enum Action
{
    ACTION_MOVE_CAMERA_FORWARD,
    ACTION_MOVE_CAMERA_BACKWARD,
    ACTION_MOVE_CAMERA_LEFT,
    ACTION_MOVE_CAMERA_RIGHT,
    ACTION_MOVE_OBJECTS,
    ACTION_ROTATE_OBJECTS,
    ACTION_SCALE_OBJECTS,
    ACTION_HIDE_OBJECTS,
    ACTION_SHOW_OBJECTS,
    ACTION_COPY_OBJECTS,
    ACTION_PASTE_OBJECTS,
    ACTION_UNDO_COMMAND,
    ACTION_REDO_COMMAND,
    TOTAL_ACTIONS
};

const char* to_c_string(Action action);

#endif // ACTION_H
