#ifndef KEY_BINDINGS_H
#define KEY_BINDINGS_H

#include "Action.h"

#include <vsg/ui/KeyEvent.h>

#include <array>

enum MyKeyModifier
{
    MY_KEY_MODIFIER_NONE   = 0x0000,
    MY_KEY_MODIFIER_LSHIFT = 0x0001,
    MY_KEY_MODIFIER_RSHIFT = 0x0002,
    MY_KEY_MODIFIER_LCTRL  = 0x0004,
    MY_KEY_MODIFIER_RCTRL  = 0x0008,
    MY_KEY_MODIFIER_LALT   = 0x0010,
    MY_KEY_MODIFIER_RALT   = 0x0020,

    MY_KEY_MODIFIER_ANYSHIFT = MY_KEY_MODIFIER_LSHIFT | MY_KEY_MODIFIER_RSHIFT,
    MY_KEY_MODIFIER_ANYCTRL  = MY_KEY_MODIFIER_LCTRL  | MY_KEY_MODIFIER_RCTRL,
    MY_KEY_MODIFIER_ANYALT   = MY_KEY_MODIFIER_LALT   | MY_KEY_MODIFIER_RALT
};

struct KeyBinding
{
    int modifiers = MY_KEY_MODIFIER_NONE;
    vsg::KeySymbol key;
};

using KeyBindings = std::array<KeyBinding, TOTAL_ACTIONS>;

#endif // KEY_BINDINGS_H
