Станция-A (Ч)	track_a_per-ch	1	1000	0
Станция-A (ЧД)	track_a_per-chd	1	1000	0
Станция-A (ЧК)	track_akol_2x5-chk	1	1500	0
Станция-A (Путь_1А)	track_a_p1a	1	1690	0
Станция-A (Путь_1А)	track_a_p1a	-1	30	0
Станция-A (Путь_1Б)	track_a_p1b	1	930	0
Станция-A (Путь_1Б)	track_a_p1b	-1	30	0
Станция-A (Путь_1Т)	track_a_p1t	1	1400	0
Станция-A (Путь_1Т)	track_a_p1t	-1	30	0
Станция-A (Путь_2А)	track_a_p2a	1	1690	0
Станция-A (Путь_2А)	track_a_p2a	-1	30	0
Станция-A (Путь_2Б)	track_a_p2b	1	1040	0
Станция-A (Путь_2Б)	track_a_p2b	-1	30	0
Станция-A (Путь_2Т)	track_a_p2t	1	1400	0
Станция-A (Путь_2Т)	track_a_p2t	-1	30	0
Станция-A (Путь_3)	track_a_p3a	1	1690	0
Станция-A (Путь_3)	track_a_p3a	-1	30	0
Станция-A (Путь_4)	track_a_p4a	1	1720	0
Станция-A (Путь_4)	track_a_p4a	-1	30	0
Станция-A (Путь_5А)	track_a_p5a	1	700	0
Станция-A (Путь_5А)	track_a_p5a	-1	100	0
Станция-A (Путь_5Б)	track_a_p5b	1	950	0
Станция-A (Путь_5Б)	track_a_p5b	-1	30	0
Станция-A (Путь_6А)	track_a_p6	1	2750	0
Станция-A (Путь_6А)	track_a_p6	-1	30	0
Станция-A (Путь_6Б)	track_a_p6b	1	600	0
Станция-A (Путь_6Б)	track_a_p6b	-1	110	0
Станция-A (Путь_7А)	track_a_p7a	1	1520	0
Станция-A (Путь_7А)	track_a_p7a	-1	30	0
Станция-A (Путь_7Б)	track_a_p7b	1	500	0
Станция-A (Путь_7Б)	track_a_p7b	-1	20	0
Станция-A (Путь_9)	track_a_p9	1	2250	0
Станция-A (Путь_9)	track_a_p2k	-1	30	0
Станция-A (Путь_11)	track_a_p11	1	2240	0
Станция-A (Путь_11)	track_a_p1k	-1	30	0
Станция-A (Н)	track_a-b_n-1	-1	30	0
Станция-A (НД)	track_a-b_nd-22	-1	30	0
Станция-A (НК)	track_akol_nk-6x1	-1	30	0
Станция-A (2Н)	track_a-d_2n-1x8	-1	30	0
Станция-B (Ч)	track_a-b_2-ch	1	1910	0
Станция-B (ЧД)	track_a-b_21-chd	1	1460	0
Станция-B (Путь_1)	track_b_p1	1	1250	0
Станция-B (Путь_2)	track_b_p2	1	1250	0
Станция-B (Путь_3)	track_b_p3	1	1250	0
Станция-B (Путь_4)	track_b_p4	1	1250	0
Станция-B (Путь_1)	track_b_p1	-1	30	0
Станция-B (Путь_2)	track_b_p2	-1	30	0
Станция-B (Путь_3)	track_b_p3	-1	30	0
Станция-B (Путь_4)	track_b_p4	-1	30	0
Станция-B (Н)	track_b-c_n-1	-1	30	0
Станция-B (НД)	track_b-c_nd-22	-1	30	0
Станция-C (Ч)	track_b-c_2-ch	1	1910	0
Станция-C (ЧД)	track_b-c_21-chd	1	1460	0
Станция-C (Путь_1)	track_c_p1	1	1250	0
Станция-C (Путь_2)	track_c_p2	1	1250	0
Станция-C (Путь_3)	track_c_p3	1	1250	0
Станция-C (Путь_4)	track_c_p4	1	1250	0
Станция-C (Путь_1)	track_c_p1	-1	30	0
Станция-C (Путь_2)	track_c_p2	-1	30	0
Станция-C (Путь_3)	track_c_p3	-1	30	0
Станция-C (Путь_4)	track_c_p4	-1	30	0
Станция-C (Н)	track_c-d_n-1	-1	30	0
Станция-C (НД)	track_c-d_nd-22	-1	30	0
Станция-D (Ч)	track_a-d_7x2-ch	1	1960	0
Станция-D (Путь_1)	track_d_p1	1	900	0
Станция-D (Путь_2)	track_d_p2	1	890	0
Станция-D (Путь_1)	track_d_p1	-1	30	0
Станция-D (Путь_2)	track_d_p2	-1	30	0