#ifndef     VEHICLE_API_H
#define     VEHICLE_API_H

#include    "vehicle.h"
#include    "physics.h"

#include    "airdistributor.h"
#include    "automatic-train-stop.h"
#include    "brake-auto-mode.h"
#include    "brake-crane.h"
#include    "brake-lock.h"
#include    "brake-mech.h"
#include    "coupling.h"
#include    "coupling-operating-rod.h"
#include    "electro-airdistributor.h"
#include    "epb-converter.h"
#include    "epb-2line-control.h"
#include    "loco-crane.h"
#include    "motor-compressor-ac.h"
#include    "motor-compressor-dc.h"
#include    "oscillator.h"
#include    "pantograph.h"
#include    "pneumo-anglecock.h"
#include    "pneumo-hose-epb.h"
#include    "pneumo-hose.h"
#include    "pneumo-reducer.h"
#include    "pneumo-relay.h"
#include    "pneumo-splitter.h"
#include    "pneumo-switching-valve.h"
#include    "pressure-regulator.h"
#include    "protective-device.h"
#include    "reservoir.h"
#include    "switcher.h"
#include    "traction-controller.h"
#include    "train-horn.h"
#include    "registrator.h"

#endif // VEHICLE_API_H
