#include "settings.h"

settings_t::settings_t()
    : vehicles_pos_update_interval(70)
    , vehicles_state_update_interval(100)
    , vehicle_controled_update_interval(70)
    , client_delay(100)
    , route_dir_name("")
    , route_dir_full_path("")
    , x(50)
    , y(50)
    , width(1280)
    , height(720)
    , fullscreen(false)
    , vsync(true)
    , fovy(30.0)
    , fovy_min(2.0)
    , fovy_max(120.0)
    , zNear(1.0)
    , zFar(1000.0)
    , screen_number(0)
    , name("viewer")
    , window_decoration(true)
    , double_buffer(true)
    , samples(4)
    , persistence(0.05)
    , eye_height(3.0f)
    , direction(1)
    , notify_level("INFO")
    , view_distance(1000.0f)
    , ext_cam_init_dist(25.0f)
    , ext_cam_init_height(3.0f)
    , ext_cam_init_shift(0.0f)
    , ext_cam_rot_coeff(1.0f)
    , ext_cam_speed(5.0f)
    , ext_cam_speed_coeff(10.0f)
    , ext_cam_min_dist(5.0f)
    , ext_cam_init_angle_H(0.0f)
    , ext_cam_init_angle_V(0.0f)
    , free_cam_init_pos(vsg::vec3(2.5f, 0.0f, 1.75f))
    , free_cam_rot_coeff(1.0f)
    , free_cam_speed(5.0f)
    , free_cam_speed_coeff(10.0f)
    , free_cam_fovy_step(1.0)
    , cabine_cam_rot_coeff(1.0f)
    , cabine_cam_fovy_step(1.0)
    , cabine_cam_speed(5.0f)
    , cabine_cam_z_min(-1.0f)
    , cabine_cam_z_max(0.5f)
    , stat_cam_dist(8.0f)
    , stat_cam_height(1.75f)
    , stat_cam_shift(150.0f)
    , interval(10)
{
}
