#include "settings.h"

#include "tcp-client.h"

#include <vsg/maths/vec3.h>

#include <string>

settings_t::settings_t()
    : tcp_config()
    , vehicles_pos_update_interval(70)
    , vehicles_state_update_interval(100)
    , vehicle_controled_update_interval(70)
    , client_delay(100)
    , route_dir_name("")
    , route_dir_full_path("")
    , x(50)
    , y(50)
    , width(1280)
    , height(720)
    , fullscreen(false)
    , vsync(true)
    , fovy(64.0)
    , fovy_min(2.0)
    , fovy_max(100.0)
    , pitch_min(-70.0)
    , pitch_max(70.0)
    , zNear(1.0)
    , zFar(1000.0)
    , screen_number(0)
    , name("viewer")
    , window_decoration(true)
    , double_buffer(true)
    , samples(4)
    , persistence(0.05)
    , notify_level("INFO")
    , view_distance(1000.0)
    , ext_cam_init_dist(25.0)
    , ext_cam_init_height(3.0)
    , ext_cam_init_shift(0.0)
    , ext_cam_rot_coeff(1.0)
    , ext_cam_speed(5.0)
    , ext_cam_speed_coeff(10.0)
    , ext_cam_min_dist(5.0)
    , ext_cam_init_angle_H(0.0)
    , ext_cam_init_angle_V(0.0)
    , free_cam_init_pos(2.5, 0.0, 1.75)
    , free_cam_speed_keyboard(5.0)
    , free_cam_speed_mouse(200.0)
    , free_cam_speed_coeff(sqrt(2.0))
    , free_cam_rotate_keyboard(0.05)
    , free_cam_rotate_mouse(0.5)
    , free_cam_height_step(0.2)
    , free_cam_fovy_coeff(cbrt(2.0))
    , default_driver_pos(0.0, 0.0, 3.5)
    , cabine_speed_keyboard(2.0)
    , cabine_speed_mouse(100.0)
    , cabine_speed_coeff(sqrt(2.0))
    , cabine_rotate_keyboard(0.05)
    , cabine_rotate_mouse(0.5)
    , cabine_height_step(0.1)
    , cabine_fovy_coeff(cbrt(2.0))
    , cabine_z_min(-1.0)
    , cabine_z_max(0.5)
    , stat_cam_dist(8.0)
    , stat_cam_height(1.75)
    , stat_cam_shift(150.0)
    , interval(10)
{
}
