#ifndef     IO_CONTROLLER_KEYMAP_H
#define     IO_CONTROLLER_KEYMAP_H

#include    <QMap>
#include    <key-symbols.h>

//------------------------------------------------------------------------------
//
//------------------------------------------------------------------------------
static const QMap<QString, std::uint16_t> KeySymbolsRRSMap =
    {
        {"KEY_Space", KEY_Space},
        {"KEY_Quote", KEY_Quote},
        {"KEY_Comma", KEY_Comma},
        {"KEY_Minus", KEY_Minus},
        {"KEY_Period", KEY_Period},
        {"KEY_Slash", KEY_Slash},
        {"KEY_0", KEY_0},
        {"KEY_1", KEY_1},
        {"KEY_2", KEY_2},
        {"KEY_3", KEY_3},
        {"KEY_4", KEY_4},
        {"KEY_5", KEY_5},
        {"KEY_6", KEY_6},
        {"KEY_7", KEY_7},
        {"KEY_8", KEY_8},
        {"KEY_9", KEY_9},
        {"KEY_Semicolon", KEY_Semicolon},
        {"KEY_Equals", KEY_Equals},
        {"KEY_Leftbracket", KEY_Leftbracket},
        {"KEY_Backslash", KEY_Backslash},
        {"KEY_Rightbracket", KEY_Rightbracket},
        {"KEY_A", KEY_A},
        {"KEY_B", KEY_B},
        {"KEY_C", KEY_C},
        {"KEY_D", KEY_D},
        {"KEY_E", KEY_E},
        {"KEY_F", KEY_F},
        {"KEY_G", KEY_G},
        {"KEY_H", KEY_H},
        {"KEY_I", KEY_I},
        {"KEY_J", KEY_J},
        {"KEY_K", KEY_K},
        {"KEY_L", KEY_L},
        {"KEY_M", KEY_M},
        {"KEY_N", KEY_N},
        {"KEY_O", KEY_O},
        {"KEY_P", KEY_P},
        {"KEY_Q", KEY_Q},
        {"KEY_R", KEY_R},
        {"KEY_S", KEY_S},
        {"KEY_T", KEY_T},
        {"KEY_U", KEY_U},
        {"KEY_V", KEY_V},
        {"KEY_W", KEY_W},
        {"KEY_X", KEY_X},
        {"KEY_Y", KEY_Y},
        {"KEY_Z", KEY_Z},
        {"KEY_Tilde", KEY_Tilde},
        {"KEY_BackSpace", KEY_BackSpace},
        {"KEY_Insert", KEY_Insert},
        {"KEY_KP_Multiply", KEY_KP_Multiply},
        {"KEY_KP_Add", KEY_KP_Add},
        {"KEY_KP_Subtract", KEY_KP_Subtract},
        {"KEY_KP_Decimal", KEY_KP_Decimal},
        {"KEY_KP_Divide", KEY_KP_Divide},
        {"KEY_KP_0", KEY_KP_0},
        {"KEY_KP_1", KEY_KP_1},
        {"KEY_KP_2", KEY_KP_2},
        {"KEY_KP_3", KEY_KP_3},
        {"KEY_KP_4", KEY_KP_4},
        {"KEY_KP_5", KEY_KP_5},
        {"KEY_KP_6", KEY_KP_6},
        {"KEY_KP_7", KEY_KP_7},
        {"KEY_KP_8", KEY_KP_8},
        {"KEY_KP_9", KEY_KP_9},
        {"KEY_F1", KEY_F1},
        {"KEY_F2", KEY_F2},
        {"KEY_F3", KEY_F3},
        {"KEY_F4", KEY_F4},
        {"KEY_F5", KEY_F5},
        {"KEY_F6", KEY_F6},
        {"KEY_F7", KEY_F7},
        {"KEY_F8", KEY_F8},
        {"KEY_F9", KEY_F9},
        {"KEY_F10", KEY_F10},
        {"KEY_F11", KEY_F11},
        {"KEY_F12", KEY_F12},
        {"KEY_Shift_L", KEY_Shift_L},
        {"KEY_Shift_R", KEY_Shift_R},
        {"KEY_Control_L", KEY_Control_L},
        {"KEY_Control_R", KEY_Control_R},
        {"KEY_Alt_L", KEY_Alt_L},
        {"KEY_Alt_R", KEY_Alt_R},
        {"KEY_Delete", KEY_Delete}
};

#endif
